"""empty message

Revision ID: 057670ccb562
Revises: 31e71a90174d
Create Date: 2025-03-19 23:32:05.721519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '057670ccb562'
down_revision = '31e71a90174d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('work_unit', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'work_unit')
    # ### end Alembic commands ###
