"""empty message

Revision ID: 0c53f97ca33e
Revises: ea65c3f804b9
Create Date: 2025-02-25 09:49:51.051378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c53f97ca33e'
down_revision = 'ea65c3f804b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_momo', sa.Column('status_payment', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_momo', 'status_payment')
    # ### end Alembic commands ###
