"""empty message

Revision ID: 1a68a6042588
Revises: b06ab340cade
Create Date: 2025-02-25 14:41:54.089945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a68a6042588'
down_revision = 'b06ab340cade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_online',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('order_payment_id', sa.String(length=100), nullable=False),
    sa.Column('request_payment_id', sa.String(length=50), nullable=False),
    sa.Column('result_momo', sa.JSON(), nullable=True),
    sa.Column('status_payment', sa.Boolean(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('payment_online', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'orders', 'payment_online', ['payment_online'], ['id'], onupdate='SET NULL', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'payment_online')
    op.drop_table('payment_online')
    # ### end Alembic commands ###
