"""empty message

Revision ID: 24e9126d4713
Revises: b12c2cda06fa
Create Date: 2025-04-25 16:39:35.414757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '24e9126d4713'
down_revision = 'b12c2cda06fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verity_code', sa.Column('limit', mysql.INTEGER(unsigned=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verity_code', 'limit')
    # ### end Alembic commands ###
