"""empty message

Revision ID: 31e71a90174d
Revises: 77d81733d0f8
Create Date: 2025-03-15 22:16:23.328042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31e71a90174d'
down_revision = '77d81733d0f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('social_insurance_number', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('ethnicity', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('nationality', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'nationality')
    op.drop_column('user', 'ethnicity')
    op.drop_column('user', 'social_insurance_number')
    # ### end Alembic commands ###
