"""empty message

Revision ID: 37f1c9439545
Revises: 63a825cbb03f
Create Date: 2025-02-03 22:43:27.941529

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '37f1c9439545'
down_revision = '63a825cbb03f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_report',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('profile_id', sa.String(length=50), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('kpi_score', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('reward', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('total_salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('modified_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_report_created_date'), 'salary_report', ['created_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salary_report_created_date'), table_name='salary_report')
    op.drop_table('salary_report')
    # ### end Alembic commands ###
