"""empty message

Revision ID: 382a37620bc2
Revises: 9dfbdd441ed9
Create Date: 2025-02-26 15:52:09.705758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382a37620bc2'
down_revision = '9dfbdd441ed9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_online', sa.Column('session_order_id', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'payment_online', 'session_order', ['session_order_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_online', type_='foreignkey')
    op.drop_column('payment_online', 'session_order_id')
    # ### end Alembic commands ###
