"""empty message

Revision ID: 62f100becbe6
Revises: 4bf7914a80b6
Create Date: 2025-02-03 23:08:58.903003

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '62f100becbe6'
down_revision = '4bf7914a80b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salary', sa.Column('created_date', mysql.INTEGER(unsigned=True), nullable=True))
    op.create_index(op.f('ix_salary_created_date'), 'salary', ['created_date'], unique=False)
    op.add_column('salary_report', sa.Column('salary_id', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'salary_report', 'salary', ['salary_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'salary_report', type_='foreignkey')
    op.drop_column('salary_report', 'salary_id')
    op.drop_index(op.f('ix_salary_created_date'), table_name='salary')
    op.drop_column('salary', 'created_date')
    # ### end Alembic commands ###
