"""empty message

Revision ID: 63a825cbb03f
Revises: c8c0352732f3
Create Date: 2025-02-03 22:32:19.096253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '63a825cbb03f'
down_revision = 'c8c0352732f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.Column('finish_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('profile_id', sa.String(length=50), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('check_in', sa.Time(), nullable=True),
    sa.Column('check_out', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_storage',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('profile_id', sa.String(length=50), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('document_url', sa.String(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salary',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('profile_id', sa.String(length=50), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('kpi_salary', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('allowance_salary', mysql.INTEGER(unsigned=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salary')
    op.drop_table('document_storage')
    op.drop_table('attendance')
    op.drop_table('profile')
    # ### end Alembic commands ###
