"""empty message

Revision ID: 7205a0924c23
Revises: 06951481f99f
Create Date: 2025-04-02 17:45:57.911989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7205a0924c23'
down_revision = '06951481f99f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('is_delete', sa.Boolean(), nullable=False))
    op.add_column('shipper', sa.Column('is_delete', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipper', 'is_delete')
    op.drop_column('product', 'is_delete')
    # ### end Alembic commands ###
