"""empty message

Revision ID: 75f90d36f2e7
Revises: 382a37620bc2
Create Date: 2025-02-27 09:38:41.546379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75f90d36f2e7'
down_revision = '382a37620bc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_online', sa.Column('user_id', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'payment_online', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_online', type_='foreignkey')
    op.drop_column('payment_online', 'user_id')
    # ### end Alembic commands ###
