"""empty message

Revision ID: 793a9f5b45c7
Revises: 31e71a90174d
Create Date: 2025-03-22 15:24:20.390629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '793a9f5b45c7'
down_revision = '31e71a90174d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('is_super_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'is_super_admin')
    # ### end Alembic commands ###
