"""empty message

Revision ID: 7da748b867a2
Revises: 1a68a6042588
Create Date: 2025-02-25 15:50:31.796365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7da748b867a2'
down_revision = '1a68a6042588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_online', sa.Column('created_date', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_online', 'created_date')
    # ### end Alembic commands ###
