"""empty message

Revision ID: 9b0ced08e1e8
Revises: b06ab340cade
Create Date: 2025-02-25 10:55:03.016822

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9b0ced08e1e8'
down_revision = 'b06ab340cade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_online',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('order_momo_id', sa.String(length=100), nullable=False),
    sa.Column('request_momo_id', sa.String(length=50), nullable=False),
    sa.Column('mac_signature', sa.Text(), nullable=False),
    sa.Column('result_momo', sa.JSON(), nullable=True),
    sa.Column('status_payment', sa.Boolean(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('payment_momo')
    op.add_column('orders', sa.Column('payment_online', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'orders', 'payment_online', ['payment_online'], ['id'], onupdate='SET NULL', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'payment_online')
    op.create_table('payment_momo',
    sa.Column('id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('order_momo_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('request_momo_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('result_momo', mysql.JSON(), nullable=True),
    sa.Column('status_payment', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('payment_online')
    # ### end Alembic commands ###
