"""empty message

Revision ID: b06ab340cade
Revises: a44b18ddbcee
Create Date: 2025-02-18 21:24:59.769886

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b06ab340cade'
down_revision = 'a44b18ddbcee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('type_product', sa.Column('created_date', mysql.INTEGER(unsigned=True), nullable=True))
    op.add_column('type_product', sa.Column('modified_date', mysql.INTEGER(unsigned=True), nullable=True))
    op.create_index(op.f('ix_type_product_created_date'), 'type_product', ['created_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_type_product_created_date'), table_name='type_product')
    op.drop_column('type_product', 'modified_date')
    op.drop_column('type_product', 'created_date')
    # ### end Alembic commands ###
