"""empty message

Revision ID: be8ac818ea67
Revises: 
Create Date: 2025-04-03 16:56:59.199800

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be8ac818ea67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('province', sa.Text(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('district', sa.Text(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('ward', sa.Text(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('community',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255, collation='utf8mb4_vietnamese_ci'), nullable=False),
    sa.Column('description', sa.String(length=255, collation='utf8mb4_vietnamese_ci'), nullable=True),
    sa.Column('created_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('modified_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_created_date'), 'community', ['created_date'], unique=False)
    op.create_table('document_storage',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255, collation='utf8mb4_vietnamese_ci'), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_template',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('template_code', sa.String(length=200), nullable=True),
    sa.Column('object', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('file_name', sa.String(length=255, collation='utf8mb4_vietnamese_ci'), nullable=True),
    sa.Column('created_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_created_date'), 'files', ['created_date'], unique=False)
    op.create_table('group',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=100, collation='utf8mb4_vietnamese_ci'), nullable=False),
    sa.Column('description', sa.String(length=500, collation='utf8mb4_vietnamese_ci'), nullable=True),
    sa.Column('created_date', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('modified_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_group_created_date'), 'group', ['created_date'], unique=False)
    op.create_table('permission',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100, collation='utf8mb4_vietnamese_ci'), nullable=False),
    sa.Column('resource', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('region',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.Text(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('region', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100, collation='utf8mb4_vietnamese_ci'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.Column('created_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('modified_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('shipper',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.Column('name', sa.Text(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_product',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('key', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('type_id', sa.String(length=50), nullable=True),
    sa.Column('created_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('modified_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['type_product.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_type_product_created_date'), 'type_product', ['created_date'], unique=False)
    op.create_table('file_link',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('file_id', sa.String(length=50), nullable=True),
    sa.Column('table_id', sa.String(length=50), nullable=True),
    sa.Column('table_type', sa.String(length=50), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('created_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_link_created_date'), 'file_link', ['created_date'], unique=False)
    op.create_table('group_role',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('role_id', sa.String(length=50), nullable=True),
    sa.Column('group_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_role_group_id'), 'group_role', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_role_role_id'), 'group_role', ['role_id'], unique=False)
    op.create_table('price_ship',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('region_id', sa.String(length=50), nullable=True),
    sa.Column('shipper_id', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shipper_id'], ['shipper.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.Text(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('describe', sa.Text(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('type_product_id', sa.String(length=50), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.Column('original_price', sa.BigInteger(), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('discount_from_date', sa.Integer(), nullable=True),
    sa.Column('discount_to_date', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('modified_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type_product_id'], ['type_product.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permission',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('role_id', sa.String(length=50), nullable=False),
    sa.Column('permission_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_permission_permission_id'), 'role_permission', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permission_role_id'), 'role_permission', ['role_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100, collation='utf8mb4_vietnamese_ci'), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.Boolean(), nullable=False),
    sa.Column('full_name', sa.String(length=100, collation='utf8mb4_vietnamese_ci'), nullable=False),
    sa.Column('avatar_id', sa.String(length=50), nullable=True),
    sa.Column('birthday', sa.DATE(), nullable=False),
    sa.Column('created_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('modified_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('address_id', sa.String(length=50), nullable=True),
    sa.Column('detail_address', sa.String(length=100, collation='utf8mb4_vietnamese_ci'), nullable=True),
    sa.Column('last_seen_notify', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('group_id', sa.String(length=50), nullable=True),
    sa.Column('identification_card', sa.String(length=100), nullable=True),
    sa.Column('tax_code', sa.String(length=100, collation='utf8mb4_vietnamese_ci'), nullable=True),
    sa.Column('social_insurance_number', sa.String(length=100, collation='utf8mb4_vietnamese_ci'), nullable=True),
    sa.Column('join_date', sa.DATE(), nullable=True),
    sa.Column('finish_date', sa.DATE(), nullable=True),
    sa.Column('number_dependent', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('ethnicity', sa.String(length=100, collation='utf8mb4_vietnamese_ci'), nullable=True),
    sa.Column('nationality', sa.String(length=100, collation='utf8mb4_vietnamese_ci'), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['avatar_id'], ['files.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_created_date'), 'user', ['created_date'], unique=False)
    op.create_table('address_order',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('address_id', sa.String(length=50), nullable=True),
    sa.Column('detail_address', sa.String(length=100, collation='utf8mb4_vietnamese_ci'), nullable=True),
    sa.Column('full_name', sa.String(length=100, collation='utf8mb4_vietnamese_ci'), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=150, collation='utf8mb4_vietnamese_ci'), nullable=False),
    sa.Column('body', sa.Text(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('body_type', sa.String(length=50), nullable=True),
    sa.Column('created_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('modified_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('community_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_created_date'), 'article', ['created_date'], unique=False)
    op.create_table('attendance',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('check_in', sa.Time(), nullable=True),
    sa.Column('check_out', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('color',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.Text(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('created_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_color_created_date'), 'color', ['created_date'], unique=False)
    op.create_table('notify',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('modified_date', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('notify_type', sa.String(length=50), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('action_id', sa.String(length=50), nullable=True),
    sa.Column('unread', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reaction',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('reactable_id', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('vote', sa.Boolean(), nullable=False),
    sa.Column('created_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('modified_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reaction_created_date'), 'reaction', ['created_date'], unique=False)
    op.create_table('session_order',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('size',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.Text(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('created_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_size_created_date'), 'size', ['created_date'], unique=False)
    op.create_table('staff_document_file',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('document_id', sa.String(length=50), nullable=False),
    sa.Column('file_id', sa.String(length=50), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('created_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('modified_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document_storage.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_document_file_created_date'), 'staff_document_file', ['created_date'], unique=False)
    op.create_table('verity_code',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_tag_product',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('article_id', sa.String(length=50), nullable=True),
    sa.Column('product_id', sa.String(length=50), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_items',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('color_id', sa.String(length=50), nullable=True),
    sa.Column('size_id', sa.String(length=50), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('modified_date', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('product_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['color.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['size_id'], ['size.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('body', sa.Text(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('body_type', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('article_id', sa.String(length=50), nullable=False),
    sa.Column('ancestry_id', sa.String(length=50), nullable=True),
    sa.Column('created_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('modified_date', mysql.INTEGER(unsigned=True), nullable=True),
    sa.ForeignKeyConstraint(['ancestry_id'], ['comment.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_created_date'), 'comment', ['created_date'], unique=False)
    op.create_table('notify_detail',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('action_id', sa.String(length=50), nullable=True),
    sa.Column('notify_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['notify_id'], ['notify.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_online',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('order_payment_id', sa.String(length=100), nullable=False),
    sa.Column('request_payment_id', sa.String(length=50), nullable=False),
    sa.Column('session_order_id', sa.String(length=50), nullable=True),
    sa.Column('result_payment', sa.JSON(), nullable=True),
    sa.Column('status_payment', sa.Boolean(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_order_id'], ['session_order.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.String(length=100, collation='utf8mb4_vietnamese_ci'), nullable=True),
    sa.Column('phone_number', sa.String(length=100), nullable=True),
    sa.Column('address_id', sa.String(length=50), nullable=True),
    sa.Column('detail_address', sa.String(length=100, collation='utf8mb4_vietnamese_ci'), nullable=True),
    sa.Column('count', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('modified_date', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('ship_id', sa.String(length=50), nullable=True),
    sa.Column('price_ship', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('payment_status', sa.Boolean(), nullable=False),
    sa.Column('payment_online_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_online_id'], ['payment_online.id'], onupdate='SET NULL', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ship_id'], ['shipper.id'], onupdate='SET NULL', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_address_id'), 'orders', ['address_id'], unique=False)
    op.create_table('session_order_cart_items',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.String(length=50), nullable=False),
    sa.Column('session_order_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['cart_items.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_order_id'], ['session_order.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=True),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('count', sa.BigInteger(), nullable=True),
    sa.Column('size_id', sa.String(length=50), nullable=True),
    sa.Column('color_id', sa.String(length=50), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('modified_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['color.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], onupdate='SET NULL', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['size_id'], ['size.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_report',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.String(length=100, collation='utf8mb4_vietnamese_ci'), nullable=True),
    sa.Column('order_id', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('result', sa.Text(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('result_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_report')
    op.drop_table('order_items')
    op.drop_table('session_order_cart_items')
    op.drop_index(op.f('ix_orders_address_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('payment_online')
    op.drop_table('notify_detail')
    op.drop_index(op.f('ix_comment_created_date'), table_name='comment')
    op.drop_table('comment')
    op.drop_table('cart_items')
    op.drop_table('article_tag_product')
    op.drop_table('verity_code')
    op.drop_index(op.f('ix_staff_document_file_created_date'), table_name='staff_document_file')
    op.drop_table('staff_document_file')
    op.drop_index(op.f('ix_size_created_date'), table_name='size')
    op.drop_table('size')
    op.drop_table('session_order')
    op.drop_index(op.f('ix_reaction_created_date'), table_name='reaction')
    op.drop_table('reaction')
    op.drop_table('notify')
    op.drop_index(op.f('ix_color_created_date'), table_name='color')
    op.drop_table('color')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_article_created_date'), table_name='article')
    op.drop_table('article')
    op.drop_table('address_order')
    op.drop_index(op.f('ix_user_created_date'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_role_permission_role_id'), table_name='role_permission')
    op.drop_index(op.f('ix_role_permission_permission_id'), table_name='role_permission')
    op.drop_table('role_permission')
    op.drop_table('product')
    op.drop_table('price_ship')
    op.drop_index(op.f('ix_group_role_role_id'), table_name='group_role')
    op.drop_index(op.f('ix_group_role_group_id'), table_name='group_role')
    op.drop_table('group_role')
    op.drop_index(op.f('ix_file_link_created_date'), table_name='file_link')
    op.drop_table('file_link')
    op.drop_index(op.f('ix_type_product_created_date'), table_name='type_product')
    op.drop_table('type_product')
    op.drop_table('shipper')
    op.drop_table('role')
    op.drop_table('region')
    op.drop_table('permission')
    op.drop_index(op.f('ix_group_created_date'), table_name='group')
    op.drop_table('group')
    op.drop_index(op.f('ix_files_created_date'), table_name='files')
    op.drop_table('files')
    op.drop_table('email_template')
    op.drop_table('document_storage')
    op.drop_index(op.f('ix_community_created_date'), table_name='community')
    op.drop_table('community')
    op.drop_table('address')
    # ### end Alembic commands ###
