"""empty message

Revision ID: ea65c3f804b9
Revises: b06ab340cade
Create Date: 2025-02-24 15:21:54.270197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea65c3f804b9'
down_revision = 'b06ab340cade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_momo',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('order_momo_id', sa.String(length=100), nullable=False),
    sa.Column('request_momo_id', sa.String(length=50), nullable=False),
    sa.Column('result_momo', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('online_payment', sa.Boolean(), nullable=False))
    op.add_column('orders', sa.Column('payment_momo_id', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'orders', 'payment_momo', ['payment_momo_id'], ['id'], onupdate='SET NULL', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'payment_momo_id')
    op.drop_column('orders', 'online_payment')
    op.drop_table('payment_momo')
    # ### end Alembic commands ###
