"""empty message

Revision ID: eb63493673fc
Revises: 3a5a6b38c2b0
Create Date: 2025-03-28 10:00:18.329972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb63493673fc'
down_revision = '3a5a6b38c2b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notify',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('notice_type', sa.String(length=50), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('action_id', sa.String(length=50), nullable=True),
    sa.Column('unread', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notify_detail',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('created_date', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('action_id', sa.String(length=50), nullable=True),
    sa.Column('notify_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['notify_id'], ['notify.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notify_detail')
    op.drop_table('notify')
    # ### end Alembic commands ###
