services:
  redis:
    image: redis:alpine  # Using a lightweight Redis image
    container_name: redis_server  # Name of the container
    restart: always  # Automatically restart the container unless it is manually stopped
    command: redis-server --save 20 1 --loglevel warning --requirepass cuong942002
    ports:
      - "6379:6379"  # Expose Redis port 6379
    volumes:
      - redis_data:/data  # Store Redis data on a volume for persistenc
volumes:
  redis_data:  # Define a named volume for persistent storage
