global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'flask-app'
    metrics_path: /api/v1/monitor/metrics
    static_configs:
      - targets: ['app:5012']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
